export const SITE_CONFIG = {
  name: "Waffle Station Coffee Shop",
  tagline: "Waffles Artesanais & Cafés Especiais",
  description:
    "Somos um refúgio acolhedor para quem aprecia bons momentos. Em um ambiente intimista e convidativo, servimos cafés especiais e waffles artesanais feitos na hora.",
  address: "Av. Guilherme Polydoro, 23 - Jardim Zaira, Mauá - SP",
  phone: "(11) 97061-4479",
  phoneRaw: "5511970614479",
  whatsapp: "5511970614479",
  instagram: "https://www.instagram.com/wafflestationmaua/",
  tiktok: "https://www.tiktok.com/@wafflestationmaua",
  ifood: "https://www.ifood.com.br/delivery/maua-sp/waffle-station-cafeteria-jardim-zaira/b7377311-0483-49db-bd55-70bd00252480?UTM_Medium=share",
  priceRange: "R$20 – R$40",
  googleMapsEmbed:
    "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3653.4!2d-46.46!3d-23.67!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMjPCsDQwJzEyLjAiUyA0NsKwMjcnMzYuMCJX!5e0!3m2!1spt-BR!2sbr!4v1234567890",
  hours: [
    { day: "Segunda – Sexta", time: "08:00 – 20:00" },
    { day: "Sábado", time: "08:00 – 21:00" },
    { day: "Domingo", time: "09:00 – 18:00" },
  ],
};

export const MENU_CATEGORIES = [
  {
    id: "waffles-doces",
    name: "Waffles Doces",
    icon: "🧇",
    description: "Artesanais, crocantes por fora e macios por dentro",
    items: [
      {
        id: 1,
        name: "Waffle Clássico",
        description: "Manteiga, mel e açúcar de baunilha",
        price: 22,
        badge: "Favorito",
        tags: ["clássico", "vegetariano"],
      },
      {
        id: 2,
        name: "Waffle Nutella & Morango",
        description: "Camadas generosas de Nutella com morangos frescos e chantilly",
        price: 29,
        badge: "Mais Pedido",
        tags: ["chocolate", "frutas"],
      },
      {
        id: 3,
        name: "Waffle Brigadeiro",
        description: "Calda de brigadeiro artesanal com granulado e sorvete de creme",
        price: 32,
        badge: null,
        tags: ["chocolate", "sorvete"],
      },
      {
        id: 4,
        name: "Waffle Red Velvet",
        description: "Massa avermelhada com cream cheese e calda de frutas vermelhas",
        price: 34,
        badge: "Premium",
        tags: ["especial", "cream cheese"],
      },
      {
        id: 5,
        name: "Waffle Doce de Leite",
        description: "Doce de leite argentino, banana caramelizada e nozes",
        price: 30,
        badge: null,
        tags: ["caramelizado", "frutas"],
      },
      {
        id: 6,
        name: "Waffle Frutas Vermelhas",
        description: "Mix de frutas vermelhas, calda e chantilly artesanal",
        price: 28,
        badge: null,
        tags: ["frutas", "light"],
      },
    ],
  },
  {
    id: "waffles-salgados",
    name: "Waffles Salgados",
    icon: "🥪",
    description: "A surpresa saborosa da nossa cozinha",
    items: [
      {
        id: 7,
        name: "Waffle Frango & Cheddar",
        description: "Frango desfiado temperado, cheddar cremoso e cebolinha",
        price: 30,
        badge: "Destaque",
        tags: ["proteína", "queijo"],
      },
      {
        id: 8,
        name: "Waffle Bacon & Ovo",
        description: "Bacon crocante, ovo estrelado e queijo derretido",
        price: 32,
        badge: null,
        tags: ["café da manhã", "proteína"],
      },
      {
        id: 9,
        name: "Waffle Caprese",
        description: "Tomate, mussarela fresca, rúcula e pesto de manjericão",
        price: 28,
        badge: "Veggie",
        tags: ["vegetariano", "italiano"],
      },
      {
        id: 10,
        name: "Waffle Peperoni",
        description: "Molho de tomate caseiro, peperoni e mix de queijos",
        price: 33,
        badge: null,
        tags: ["italiano", "queijo"],
      },
    ],
  },
  {
    id: "cafes-especiais",
    name: "Cafés Especiais",
    icon: "☕",
    description: "Grãos selecionados, extração precisa",
    items: [
      {
        id: 11,
        name: "Espresso Clássico",
        description: "Shot perfeito de blend especial da casa, 30ml de pura intensidade",
        price: 8,
        badge: null,
        tags: ["intenso", "puro"],
      },
      {
        id: 12,
        name: "Cappuccino Italiano",
        description: "Espresso, leite vaporizado e espuma densa de leite integral",
        price: 16,
        badge: "Favorito",
        tags: ["clássico", "cremoso"],
      },
      {
        id: 13,
        name: "Latte Artesanal",
        description: "Espresso duplo com leite vaporizado suave e latte art",
        price: 18,
        badge: null,
        tags: ["suave", "cremoso"],
      },
      {
        id: 14,
        name: "Flat White",
        description: "Ristretto duplo com microespuma aveludada, estilo australiano",
        price: 19,
        badge: "Premium",
        tags: ["intenso", "aveludado"],
      },
      {
        id: 15,
        name: "Café de Filtro",
        description: "Extração lenta por hario v60, grão de origem única",
        price: 15,
        badge: null,
        tags: ["filtrado", "origem única"],
      },
      {
        id: 16,
        name: "Irish Coffee",
        description: "Café quente, whisky irlandês e chantilly fresco",
        price: 28,
        badge: "Especial",
        tags: ["adulto", "premium"],
      },
    ],
  },
  {
    id: "bebidas-geladas",
    name: "Bebidas Geladas",
    icon: "🧊",
    description: "Refrescantes e cheias de sabor",
    items: [
      {
        id: 17,
        name: "Cold Brew",
        description: "Café extraído a frio por 24h, suave e encorpado",
        price: 18,
        badge: "Exclusivo",
        tags: ["gelado", "intenso"],
      },
      {
        id: 18,
        name: "Iced Caramel Latte",
        description: "Espresso, leite gelado, calda de caramelo artesanal e gelo",
        price: 22,
        badge: "Mais Pedido",
        tags: ["doce", "gelado"],
      },
      {
        id: 19,
        name: "Frappuccino da Casa",
        description: "Café batido com leite, calda de chocolate e chantilly",
        price: 24,
        badge: null,
        tags: ["gelado", "cremoso"],
      },
      {
        id: 20,
        name: "Matcha Latte Gelado",
        description: "Chá matcha premium japonês com leite de amêndoas",
        price: 22,
        badge: "Novidade",
        tags: ["matcha", "vegano"],
      },
      {
        id: 21,
        name: "Limonada Suíça",
        description: "Limão, leite condensado, creme de leite e hortelã",
        price: 18,
        badge: null,
        tags: ["refrescante", "cremoso"],
      },
    ],
  },
  {
    id: "sobremesas",
    name: "Sobremesas",
    icon: "🍰",
    description: "O final perfeito para sua visita",
    items: [
      {
        id: 22,
        name: "Brownie com Sorvete",
        description: "Brownie quentinho de chocolate belga com sorvete de baunilha",
        price: 24,
        badge: "Favorito",
        tags: ["chocolate", "quente-frio"],
      },
      {
        id: 23,
        name: "Cheesecake de Frutas Vermelhas",
        description: "Fatia generosa de cheesecake com calda de frutas frescas",
        price: 22,
        badge: null,
        tags: ["gelado", "frutas"],
      },
      {
        id: 24,
        name: "Tiramisù",
        description: "Clássico italiano com mascarpone, café e cacau em pó",
        price: 26,
        badge: "Premium",
        tags: ["italiano", "café"],
      },
      {
        id: 25,
        name: "Cookie Artesanal",
        description: "Cookie gigante crocante com chocolate chip belga",
        price: 14,
        badge: null,
        tags: ["chocolate", "artesanal"],
      },
    ],
  },
];

export const REVIEWS = [
  {
    id: 1,
    name: "Ana Carolina M.",
    rating: 5,
    date: "há 2 semanas",
    text: "Melhor lugar para ir com a família! Os waffles são incríveis e o ambiente é super aconchegante. Minha filha amou o waffle de Nutella. Com certeza voltaremos!",
    avatar: "A",
    highlight: "Ótimo para família",
  },
  {
    id: 2,
    name: "Rafael Souza",
    rating: 5,
    date: "há 1 mês",
    text: "Waffles maravilhosos e cafés incríveis! Nunca tinha experimentado um flat white tão bem feito em Mauá. Os grãos são de qualidade excepcional. Virei cliente fiel.",
    avatar: "R",
    highlight: "Cafés excepcionais",
  },
  {
    id: 3,
    name: "Fernanda Lima",
    rating: 5,
    date: "há 3 semanas",
    text: "Atendimento excelente e ambiente absolutamente aconchegante. Parece que você entra em outro mundo. O cold brew é o melhor que já tomei. Recomendo demais!",
    avatar: "F",
    highlight: "Ambiente único",
  },
  {
    id: 4,
    name: "Lucas Mendes",
    rating: 5,
    date: "há 5 dias",
    text: "Descobri esse lugar por acaso e foi uma das melhores surpresas. O waffle de bacon com ovo é de outro nível. Preço justo para a qualidade oferecida. 10/10!",
    avatar: "L",
    highlight: "Custo-benefício",
  },
  {
    id: 5,
    name: "Juliana Costa",
    rating: 5,
    date: "há 2 meses",
    text: "Meu cantinho preferido em Mauá. Toda semana passo para tomar meu cappuccino e comer um brownie. A equipe já me conhece pelo nome. Isso é atendimento de verdade!",
    avatar: "J",
    highlight: "Atendimento especial",
  },
  {
    id: 6,
    name: "Pedro Alves",
    rating: 5,
    date: "há 1 semana",
    text: "Fui para comemorar o aniversário da minha namorada e foi perfeito. A decoração é linda, o food é maravilhoso e tiramos fotos lindas. Lugar para guardar na memória.",
    avatar: "P",
    highlight: "Perfeito para ocasiões especiais",
  },
];

export const GALLERY_IMAGES = [
  { id: 1, alt: "Interior aconchegante da Waffle Station", category: "ambiente" },
  { id: 2, alt: "Waffle artesanal com frutas", category: "comida" },
  { id: 3, alt: "Mesa de madeira com café e waffle", category: "comida" },
  { id: 4, alt: "Bar de café com equipamentos profissionais", category: "ambiente" },
  { id: 5, alt: "Cappuccino com latte art", category: "bebida" },
  { id: 6, alt: "Detalhe do ambiente iluminado", category: "ambiente" },
  { id: 7, alt: "Waffle de Nutella com morango", category: "comida" },
  { id: 8, alt: "Cold brew sendo preparado", category: "bebida" },
];
