export const SITE_CONFIG = {
  name: "Waffle Station Coffee Shop",
  tagline: "Waffles Artesanais & Cafés Especiais",
  description:
    "Somos um refúgio acolhedor para quem aprecia bons momentos. Em um ambiente intimista e convidativo, servimos cafés especiais e waffles artesanais feitos na hora.",
  address: "Av. Guilherme Polydoro, 23 - Jardim Zaira, Mauá - SP",
  phone: "(11) 97061-4479",
  phoneRaw: "5511970614479",
  whatsapp: "5511970614479",
  instagram: "https://www.instagram.com/wafflestationmaua/",
  tiktok: "https://www.tiktok.com/@wafflestationmaua",
  ifood:
    "https://www.ifood.com.br/delivery/maua-sp/waffle-station-cafeteria-jardim-zaira/b7377311-0483-49db-bd55-70bd00252480?UTM_Medium=share",
  priceRange: "R$8 – R$31",
  googleMapsEmbed:
    "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3653.4!2d-46.46!3d-23.67!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMjPCsDQwJzEyLjAiUyA0NsKwMjcnMzYuMCJX!5e0!3m2!1spt-BR!2sbr!4v1234567890",
  hours: [
    { day: "Segunda-feira", time: "Fechado" },
    { day: "Terça a Sexta", time: "13:00 – 19:00" },
    { day: "Sábado", time: "11:00 – 19:00" },
    { day: "Domingo", time: "09:00 – 15:00" },
  ],
};

export const MENU_CATEGORIES = [
  {
    id: "combos",
    name: "Combos",
    icon: "🎁",
    description: "Combos promocionais imperdíveis — mais sabor, melhor preço",
    items: [
      {
        id: 1,
        name: "Baby Waffle + Cappuccino",
        description:
          "1 Baby Waffle + 1 Cappuccino. A dupla perfeita para começar bem o dia!",
        price: 20.0,
        badge: "Promoção",
        tags: ["combo", "cappuccino"],
        image: "/images/menu/baby-waffle.png",
        serves: null,
        priceFrom: false,
      },
      {
        id: 2,
        name: "Waffle Pão de Queijo + Café Latte",
        description:
          "Waffle de pão de queijo Canastra com toque de parmesão + cremoso café latte com espresso encorpado e leite vaporizado.",
        price: 30.0,
        badge: "Destaque",
        tags: ["combo", "café latte", "pão de queijo"],
        image: "/images/menu/waffle-pao-queijo.png",
        serves: "1 pessoa",
        priceFrom: false,
      },
    ],
  },
  {
    id: "pao-de-queijo",
    name: "Pão de Queijo",
    icon: "🧀",
    description:
      "O sabor mineiro em versões irresistíveis — crocante por fora, macio por dentro",
    items: [
      {
        id: 3,
        name: "Rolinho de Pão de Queijo",
        description:
          "Pão de queijo fininho, dourado na chapa e enrolado quentinho. Recheável com requeijão cremoso, geleia de morango, creme de avelã ou doce de leite.",
        price: 12.5,
        badge: null,
        tags: ["pão de queijo", "lanche"],
        image: "/images/menu/waffle-pao-queijo.png",
        serves: null,
        priceFrom: false,
      },
      {
        id: 4,
        name: "Waffle de Pão de Queijo (Canastra)",
        description:
          "Sabor autêntico do pão de queijo em waffle crocante por fora e macio por dentro. Preparado com queijo Canastra de qualidade.",
        price: 21.0,
        badge: "Favorito",
        tags: ["pão de queijo", "canastra"],
        image: "/images/menu/waffle-pao-queijo.png",
        serves: "2 pessoas",
        priceFrom: false,
      },
    ],
  },
  {
    id: "waffles-doces",
    name: "Waffles Doces",
    icon: "🧇",
    description:
      "Artesanais, crocantes por fora e macios por dentro — coberturas incríveis",
    items: [
      {
        id: 5,
        name: "Waffle dos Seus Sonhos",
        description:
          "Monte seu waffle com coberturas à escolha: frutas frescas, avelã, doce de leite, cocada, goiabada, queijo e muito mais.",
        price: 11.8,
        badge: "Personalizável",
        tags: ["personalizável", "vegetariano"],
        image: "/images/menu/waffle-avela-morango.png",
        serves: "1 pessoa",
        priceFrom: true,
      },
      {
        id: 6,
        name: "Waffle com Mel, Maçã e Canela",
        description:
          "Waffle belga coberto com fatias de maçã, canela aromática e generosa dose de mel puro. Doçura natural irresistível.",
        price: 18.33,
        badge: null,
        tags: ["mel", "frutas", "canela"],
        image: "/images/menu/waffle-avela-morango.png",
        serves: "1 pessoa",
        priceFrom: false,
      },
      {
        id: 7,
        name: "Waffle com Avelã e Banana",
        description:
          "Waffle belga com creme de avelã e rodelas de banana fresca. Combinação perfeita de cremosidade e doçura.",
        price: 23.63,
        badge: null,
        tags: ["avelã", "banana"],
        image: "/images/menu/waffle-avela-morango.png",
        serves: "1 pessoa",
        priceFrom: false,
      },
      {
        id: 8,
        name: "Waffle com Goiabada Mineira e Queijo Canastra",
        description:
          "Waffle belga com goiabada mineira e queijo Canastra cremoso. Explosão de sabores brasileiros em cada mordida.",
        price: 23.36,
        badge: "Regional",
        tags: ["goiabada", "queijo", "mineiro"],
        image: "/images/menu/waffle-goiabada-queijo.png",
        serves: "1 pessoa",
        priceFrom: false,
      },
      {
        id: 9,
        name: "Waffle com Doce de Leite e Abacaxi em Calda",
        description:
          "Waffle belga com pedaços de abacaxi em calda caseira e doce de leite mineiro. Uma viagem sensorial tropical.",
        price: 27.01,
        badge: null,
        tags: ["doce de leite", "abacaxi", "tropical"],
        image: "/images/menu/waffle-avela-morango.png",
        serves: "1 pessoa",
        priceFrom: false,
      },
      {
        id: 10,
        name: "Waffle com Avelã e Morangos",
        description:
          "Waffle belga com generoso creme de avelã e fatias frescas de morangos suculentos. A combinação perfeita.",
        price: 31.22,
        badge: "Mais Pedido",
        tags: ["avelã", "morango"],
        image: "/images/menu/waffle-avela-morango.png",
        serves: null,
        priceFrom: false,
      },
      {
        id: 11,
        name: "Waffle com Doce de Leite e Uvas Verdes",
        description:
          "Waffle belga com doce de leite mineiro tradicional e uvas verdes frescas e suculentas. Uma combinação única e encantadora.",
        price: 23.47,
        badge: null,
        tags: ["doce de leite", "uva"],
        image: "/images/menu/waffle-goiabada-queijo.png",
        serves: "1 pessoa",
        priceFrom: false,
      },
    ],
  },
  {
    id: "baby-waffles",
    name: "Baby Waffles",
    icon: "🍓",
    description:
      "Versões menores, mesmo sabor incrível — perfeitos para um mimo",
    items: [
      {
        id: 12,
        name: "Baby Waffle de Avelã com Morangos",
        description:
          "Versão pequenina do waffle belga com creme de avelã e fatias frescas de morangos suculentos.",
        price: 10.99,
        badge: "Favorito",
        tags: ["avelã", "morango"],
        image: "/images/menu/baby-waffle.png",
        serves: null,
        priceFrom: false,
      },
      {
        id: 13,
        name: "Baby Waffle de Goiabada com Queijo Canastra",
        description:
          "Versão pequenina com goiabada mineira e queijo Canastra cremoso. Explosão de sabores brasileiros.",
        price: 11.39,
        badge: null,
        tags: ["goiabada", "queijo"],
        image: "/images/menu/baby-waffle.png",
        serves: "1 pessoa",
        priceFrom: false,
      },
      {
        id: 14,
        name: "Baby Waffle de Mel com Maçã e Canela",
        description:
          "Versão pequenina com fatias de maçã, toque de canela aromática e mel puro. Doçura natural irresistível.",
        price: 7.95,
        badge: null,
        tags: ["mel", "maçã", "canela"],
        image: "/images/menu/baby-waffle.png",
        serves: "1 pessoa",
        priceFrom: false,
      },
      {
        id: 15,
        name: "Baby Waffle de Avelã com Banana",
        description:
          "Versão pequenina com creme de avelã e rodelas de banana fresca. Cremosidade e doçura em cada mordida.",
        price: 8.9,
        badge: null,
        tags: ["avelã", "banana"],
        image: "/images/menu/baby-waffle.png",
        serves: "1 pessoa",
        priceFrom: false,
      },
      {
        id: 16,
        name: "Baby Waffle de Doce de Leite com Uvas Verdes",
        description:
          "Versão pequenina com doce de leite mineiro e uvas verdes frescas. Uma combinação encantadora.",
        price: 8.9,
        badge: null,
        tags: ["doce de leite", "uva"],
        image: "/images/menu/baby-waffle.png",
        serves: "1 pessoa",
        priceFrom: false,
      },
      {
        id: 17,
        name: "Baby Waffle com Doce de Leite e Abacaxi em Calda",
        description:
          "Versão pequenina com abacaxi em calda caseira e doce de leite mineiro. Uma viagem tropical em cada mordida.",
        price: 8.9,
        badge: null,
        tags: ["doce de leite", "abacaxi"],
        image: "/images/menu/baby-waffle.png",
        serves: "1 pessoa",
        priceFrom: false,
      },
      {
        id: 18,
        name: "Baby Waffle de Ganache ao Leite com Ovomaltine",
        description:
          "Baby waffle quentinho coberto com ganache de chocolate ao leite cremoso e Ovomaltine crocante.",
        price: 11.9,
        badge: "Novidade",
        tags: ["chocolate", "ovomaltine"],
        image: "/images/menu/baby-waffle.png",
        serves: null,
        priceFrom: false,
      },
      {
        id: 19,
        name: "Baby Waffle de Geléia de Morango",
        description:
          "Baby waffle quentinho coberto com geleia de morango suave e levemente ácida. Doce na medida certa.",
        price: 13.9,
        badge: null,
        tags: ["morango", "geleia"],
        image: "/images/menu/baby-waffle.png",
        serves: null,
        priceFrom: false,
      },
    ],
  },
  {
    id: "waffles-salgados",
    name: "Waffles Salgados",
    icon: "🥪",
    description:
      "A surpresa saborosa da nossa cozinha — recheios irresistíveis",
    items: [
      {
        id: 20,
        name: "Pizza de Mussarela, Tomate e Azeitona",
        description:
          "Pizza clássica em massa de waffle: mussarela derretida, tomate fresco, azeitonas e orégano. Textura única e crocante.",
        price: 24.0,
        badge: null,
        tags: ["pizza", "queijo", "italiano"],
        image: "/images/menu/waffle-salgado.png",
        serves: null,
        priceFrom: false,
      },
      {
        id: 21,
        name: "Waffle com Frango Desfiado e Requeijão",
        description:
          "Waffle crocante coberto com frango desfiado temperado e generosa camada de requeijão cremoso. Reconfortante e delicioso.",
        price: 29.0,
        badge: "Destaque",
        tags: ["frango", "requeijão"],
        image: "/images/menu/waffle-salgado.png",
        serves: "1 pessoa",
        priceFrom: false,
      },
      {
        id: 22,
        name: "Waffle Calabresa com Mussarela e Cebolas",
        description:
          "Waffle crocante com calabresa dourada, mussarela derretida e cebolas. Combinação marcante e irresistível.",
        price: 27.0,
        badge: null,
        tags: ["calabresa", "queijo"],
        image: "/images/menu/waffle-salgado.png",
        serves: null,
        priceFrom: false,
      },
    ],
  },
  {
    id: "congelados",
    name: "Congelados",
    icon: "❄️",
    description:
      "Leve a Waffle Station para casa — praticidade com sabor artesanal",
    items: [
      {
        id: 23,
        name: "4 Baby Waffles Congelados",
        description:
          "Baby waffles prontos para rechear como você ama. Aqueça no forno a 200°C por 3 a 5 minutos.",
        price: 8.0,
        badge: null,
        tags: ["congelado", "praticidade"],
        image: "/images/menu/baby-waffle.png",
        serves: "4 pessoas",
        priceFrom: false,
      },
      {
        id: 24,
        name: "4 Waffles Tradicionais Congelados",
        description:
          "Waffles tradicionais prontos para rechear como você ama. Aqueça no forno a 200°C por 3 a 5 minutos.",
        price: 16.0,
        badge: null,
        tags: ["congelado", "praticidade"],
        image: "/images/menu/waffle-avela-morango.png",
        serves: null,
        priceFrom: false,
      },
    ],
  },
  {
    id: "bebidas",
    name: "Bebidas",
    icon: "🥤",
    description:
      "Coquetéis gelados, cappuccinos e muito mais para acompanhar",
    items: [
      {
        id: 25,
        name: "Piña Colada (Sem Álcool)",
        description:
          "Bebida gelada de abacaxi e coco, cremosa, doce na medida e super refrescante. O sabor do verão sem álcool.",
        price: 17.99,
        badge: null,
        tags: ["gelado", "tropical", "sem álcool"],
        image: "/images/menu/bebida-coquetel.png",
        serves: "1 pessoa",
        priceFrom: false,
      },
      {
        id: 26,
        name: "Manhã Tropical",
        description:
          "Mistura suave de leite e leite condensado com sorvete de creme e frescor de limão. Cremosa, gelada e refrescante.",
        price: 20.0,
        badge: null,
        tags: ["gelado", "cremoso"],
        image: "/images/menu/bebida-coquetel.png",
        serves: null,
        priceFrom: false,
      },
      {
        id: 27,
        name: "Cappuccino Ganache ao Leite",
        description:
          "Cappuccino cremoso com ganache de chocolate ao leite. Doce, aveludado e irresistível.",
        price: 25.0,
        badge: "Premium",
        tags: ["cappuccino", "chocolate"],
        image: "/images/menu/bebida-coquetel.png",
        serves: null,
        priceFrom: false,
      },
      {
        id: 28,
        name: "Cappuccino Mineirinho Gelado",
        description:
          "Espresso intenso com leite cremoso, doce de leite e paçoca. Gelado, doce na medida e com toque mineiro irresistível.",
        price: 21.49,
        badge: "Regional",
        tags: ["cappuccino", "gelado", "mineiro"],
        image: "/images/menu/bebida-coquetel.png",
        serves: null,
        priceFrom: false,
      },
      {
        id: 29,
        name: "Coca-Cola Original 350ml",
        description: "Lata 350ml gelada.",
        price: 8.68,
        badge: null,
        tags: ["refrigerante", "gelado"],
        image: null,
        serves: null,
        priceFrom: false,
      },
      {
        id: 30,
        name: "Coca-Cola Zero 350ml",
        description: "Lata 350ml gelada, sem açúcar.",
        price: 8.68,
        badge: null,
        tags: ["refrigerante", "zero"],
        image: null,
        serves: null,
        priceFrom: false,
      },
      {
        id: 31,
        name: "Suco de Maracujá",
        description: "Suco de polpa de maracujá. Refrescante e natural.",
        price: 14.0,
        badge: null,
        tags: ["suco", "natural"],
        image: "/images/menu/bebida-coquetel.png",
        serves: "1 pessoa",
        priceFrom: false,
      },
      {
        id: 32,
        name: "Suco de Abacaxi",
        description: "Suco de polpa de abacaxi. Refrescante e natural.",
        price: 12.0,
        badge: null,
        tags: ["suco", "natural"],
        image: "/images/menu/bebida-coquetel.png",
        serves: "1 pessoa",
        priceFrom: false,
      },
    ],
  },
];

export const REVIEWS = [
  {
    id: 1,
    name: "Ana Carolina M.",
    rating: 5,
    date: "há 2 semanas",
    text: "Melhor lugar para ir com a família! Os waffles são incríveis e o ambiente é super aconchegante. Minha filha amou o waffle de Nutella. Com certeza voltaremos!",
    avatar: "A",
    highlight: "Ótimo para família",
  },
  {
    id: 2,
    name: "Rafael Souza",
    rating: 5,
    date: "há 1 mês",
    text: "Waffles maravilhosos e cafés incríveis! Nunca tinha experimentado um flat white tão bem feito em Mauá. Os grãos são de qualidade excepcional. Virei cliente fiel.",
    avatar: "R",
    highlight: "Cafés excepcionais",
  },
  {
    id: 3,
    name: "Fernanda Lima",
    rating: 5,
    date: "há 3 semanas",
    text: "Atendimento excelente e ambiente absolutamente aconchegante. Parece que você entra em outro mundo. O cold brew é o melhor que já tomei. Recomendo demais!",
    avatar: "F",
    highlight: "Ambiente único",
  },
  {
    id: 4,
    name: "Lucas Mendes",
    rating: 5,
    date: "há 5 dias",
    text: "Descobri esse lugar por acaso e foi uma das melhores surpresas. O waffle de frango com requeijão é de outro nível. Preço justo para a qualidade oferecida. 10/10!",
    avatar: "L",
    highlight: "Custo-benefício",
  },
  {
    id: 5,
    name: "Juliana Costa",
    rating: 5,
    date: "há 2 meses",
    text: "Meu cantinho preferido em Mauá. Toda semana passo para tomar meu cappuccino e comer um waffle. A equipe já me conhece pelo nome. Isso é atendimento de verdade!",
    avatar: "J",
    highlight: "Atendimento especial",
  },
  {
    id: 6,
    name: "Pedro Alves",
    rating: 5,
    date: "há 1 semana",
    text: "Fui para comemorar o aniversário da minha namorada e foi perfeito. A decoração é linda, o food é maravilhoso e tiramos fotos lindas. Lugar para guardar na memória.",
    avatar: "P",
    highlight: "Perfeito para ocasiões especiais",
  },
];

export const GALLERY_IMAGES = [
  { id: 1, alt: "Interior aconchegante da Waffle Station", category: "ambiente" },
  { id: 2, alt: "Waffle artesanal com frutas", category: "comida" },
  { id: 3, alt: "Mesa de madeira com café e waffle", category: "comida" },
  { id: 4, alt: "Bar de café com equipamentos profissionais", category: "ambiente" },
  { id: 5, alt: "Cappuccino com latte art", category: "bebida" },
  { id: 6, alt: "Detalhe do ambiente iluminado", category: "ambiente" },
  { id: 7, alt: "Waffle de avelã com morango", category: "comida" },
  { id: 8, alt: "Coquetel gelado sendo preparado", category: "bebida" },
];
